name: Build TeX Files

on:
  push:
    paths:
      - 'TeX/**.tex'
      - 'TeX/**.bib'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: danteev/texlive

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        run: |
          cd TeX/
          make
      - name: Upload PDF document (Projektarbeit)
        uses: actions/upload-artifact@v2
        with:
          name: Projektarbeit
          path: TeX/Projektarbeit.pdf
      - name: Upload PDF Document (Präsentation)
        uses: actions/upload-artifact@v2
        with:
          name: Präsentation
          path: TeX/Presentation.pdf

