name: Build Projektarbeit

on:
  push:
    paths:
      - 'Projektarbeit/**.tex'
      - 'Projektarbeit/**.bib'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: danteev/texlive

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        run: |
          cd Projektarbeit/
          make
      - name: Upload PDF document
        uses: actions/upload-artifact@v2
        with:
          name: Projektarbeit
          path: Projektarbeit/Projektarbeit.pdf

